spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERS-SERVICE
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTEMENT-SERVICE
          uri: lb://DEPARTEMENT-SERVICE
          predicates:
            - Path=/departement/**



    spring:
    cloud:
      gateway:
        routes:
          - id: USERS-SERVICE
            url: lb://USERS-SERVICE
            predicates:
              - Path=/users/**
            filters:
              - name: CircuitBreaker
                args:
                  name: USERS-SERVICE
                  fallbackuri: forward:/userServiceFallBackMethod
          - id: DEPARTEMENT-SERVICE
            url: lb://DEPARTEMENT-SERVICE
            predicates:
              - Path=/departement/**
            filters:
              - name: CircuitBreaker
                args:
                  name: DEPARTEMENT-SERVICE
                  fallbackuri: forward:/departementServiceFallBackMethod


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMillisecounds: 4000



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost



management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      USERS-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: